reference: /home/users/data/01_reference/human_g1k_v37/human_g1k_v37.fasta

# basic languages
java8: /home/users/cjyoon/tools/jdk1.8.0_171/bin/java


# bam processing
picard: /home/users/tools/picard/dist/picard.jar
gatk: /home/users/cjyoon/tools/GenomeAnalysisTK-3.8-1/GenomeAnalysisTK.jar
samtools: /home/users/cjyoon/anaconda3/bin/samtools
bwa: /home/users/cjyoon/anaconda3/bin/bwa
knownindel: /home/users/data/02_annotation/01_GATK/01_golden_standard/Mills_and_1000G_gold_standard.indels.b37.vcf
dbsnp: /home/users/data/02_annotation/01_GATK/02_db_snp/dbsnp_138.b37.vcf
cosmic: /home/users/data/02_annotation/03_mutect/cosmic_v71_141209.vcf
dbsnp_mutect: /home/users/data/02_annotation/03_mutect/dbsnp_132_b37.leftAligned.vcf  

# snv variant callers
freebayes: /home/users/cjyoon/anaconda3/bin/freebayes

# variant filters
passFilter: scripts/passFilter
vcfallelicprimitives: /home/users/cjyoon/anaconda3/bin/vcfallelicprimitives
vt: /home/users/cjyoon/anaconda3/bin/vt

# variant annotator
vep: /home/users/cjyoon/ensembl-vep/vep
